name: Build and push ostree container
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: quay.io/fedora/fedora-coreos:stable
      options: "--user root --privileged -v /var/tmp:/var/tmp -v /tmp:/tmp"
    strategy:
      matrix:
        release_version:
          - "40"
          - "41"
    steps:
      - uses: actions/checkout@v4
        # https://github.com/actions/checkout/issues/760
      - name: Mark git checkout as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install deps
        run: rpm-ostree install distribution-gpg-keys
      - name: Login
        run: podman login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        if: github.event_name != 'pull_request'
      - name: Build ostree container
        run: rpm-ostree compose image --format=registry --initialize-mode if-not-exists fedora-${{ matrix.release_version }}.yaml ghcr.io/${{ github.repository_owner }}/fedora-ostree-base:${{ matrix.release_version }}-${{ github.ref_name }}
